---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: devops-toolkit
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: devops-toolkit
  interval: 1m0s
  targetNamespace: staging
  values:
    image:
      tag: 2.9.17
    ingress:
      host: staging.devops-toolkit.192.168.44.100.xip.io

